import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def plot_epr_matrix():
    print("Loading data from epr_sweep_results.csv...")
    try:
        # Load data generated by the Rust engine
        df = pd.read_csv('epr_sweep_results.csv')
    except FileNotFoundError:
        print("Error: 'epr_sweep_results.csv' not found. Run the Rust program first.")
        return

    # Pivot the data to create a 5x5 matrix
    pivot_df = df.pivot(index='Alice_Angle', columns='Bob_Angle', values='Correlation')

    # Graphic style configuration (academic format)
    try:
        plt.style.use('seaborn-v0_8-whitegrid')
    except:
        plt.style.use('default')
        
    fig, ax = plt.subplots(figsize=(8, 6.5))

    # Create Heatmap
    sns.heatmap(
        pivot_df, 
        annot=True, 
        fmt=".4f", 
        cmap="coolwarm", 
        vmin=-1.0, 
        vmax=1.0, 
        square=True,
        cbar_kws={'label': 'Correlation Value $E(a, b)$'},
        linewidths=1.5,
        linecolor='#f0f0f0',
        annot_kws={'size': 11, 'weight': 'bold'}
    )

    plt.title('DWE - EPR/CHSH Spectral Sweep (5x5 Matrix)\nPopescu-Rohrlich Box Realistic Local Behavior (Detection Loophole)', fontsize=12, fontweight='bold', pad=15)
    plt.xlabel('Bob Angle $\\beta$ (Degrees)', fontsize=11, fontweight='bold')
    plt.ylabel('Alice Angle $\\alpha$ (Degrees)', fontsize=11, fontweight='bold')
    plt.tight_layout()

    # Save plot in high resolution
    plt.savefig('epr_spectral_plot.png', dpi=300)
    print("Success! Plot saved in high resolution as 'epr_spectral_plot.png'")

if __name__ == "__main__":
    plot_epr_matrix()